lerning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views


#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path("",views.index, name="index"),
    path("other/", views.other, name="other"),
    path("relative/", views.relative, name="relative"),
]

lerning_templates/lerning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.index, name="index"),
    path("other/", views.other, name="other"),
    path("relative/", views.relative, name="relative"),
    path("basic_app/", include("basic_app.urls"))
]

lerning_templates/basic_app/models.py
from django.db import models

# Create your models here.

lerning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    dict = {'text':'hello world','number':100}
    return render(request,"basic_app/index.html",context=dict)

def other(request):
    return render(request,"basic_app/other.html")

def relative(request):
    return render(request,"basic_app/relative_url_templates.html")

lerning_templates/templates/basic_app/base.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 </head>
 <body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">BRAND</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
                <li><a href="{% url 'basic_app:other' %}" class="navbar-link">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!--Anythong outside of this will be inherited if you extend-->
         
        {% endblock body_block %}

    </div>
 </body>
 </html>

lerning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_extras %}
    
{% block body_block %}

    <h1>WELCOME TO INDEX</h1>
    <h1>This is index.html showing!</h1>
    <h1>{{text | upper}}</h1>
    <h1>{{number|add:"999"}}</h1>
    <h1>{{text|cuts:'world'}}</h1>
{% endblock body_block %}

lerning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>WELCOME TO OTHERS</h1>
    <h2>This is an example of template inheritance!</h2>
{% endblock body_block %}    

lerning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">Click here to go to other page</a>
    {% comment %} no space should be given inside 'basic_app:other' {% endcomment %}
    <br>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <br>
    <a href="{% url 'basic_app:index' %}">Link to index</a>
</body>
</html>